services:
  redpanda:
    image: redpandadata/redpanda:latest
    command:
      - redpanda start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M --node-id 0 --check=false
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "bash", "-lc", "rpk cluster info || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  jaeger:
    image: jaegertracing/all-in-one:1.57
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"  # UI
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector:0.103.1
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./utils/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
    depends_on:
      - loki
      - jaeger

  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ./utils/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - api
      - worker

  loki:
    image: grafana/loki:2.9.8
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:11.2.0
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
    volumes:
      - ./utils/grafana/provisioning:/etc/grafana/provisioning
